#!/usr/bin/env node
// Install the multi-agent review pipeline into a repository.
//
//   node review-kit/install.mjs --target /path/to/repo
//   node review-kit/install.mjs                          # target = the current directory
//
// Copies the portable runtime - the scripts, the workflow, the schemas, the contract, the two
// skills - and a starter config. It deliberately does NOT decide which reviewers this repo needs,
// what routes them or what they own: that is judgement, and it is what
// <docsRoot>/review-onboarding.md (and the /review-kit skill) exists for.
//
// Existing files are left alone unless --force. Re-running is safe and is how you take an update.
//
// Options
//   --target <dir>        repository to install into (default: cwd)
//   --docs-root <dir>     where the review docs live (default: docs/agents)
//   --agents-root <dir>   where the agent files live (default: .claude/agents)
//   --review-dir <dir>    where a run writes its artefacts (default: .review)
//   --trigger <text>      the PR comment that starts a CI review (default: "@claude deep-review")
//   --corpus <mode>       native (default) - rules hand-written here, anchored, with a routing
//                         table and an index. aidd - the corpus is generated by the AIDD
//                         framework and is read-only: no routing table, no index, rules cited by
//                         path. none - the review pipeline alone.
//   --no-vendor           do not copy the kit itself into <target>/tools/review-kit
//   --no-workflow         skip the GitHub Actions workflow (local /review-pr only)
//   --no-agents-md        do not add the pointer block to AGENTS.md / CLAUDE.md
//   --force               overwrite files that already exist
//   --dry-run             print what would happen, write nothing

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const KIT = dirname(fileURLToPath(import.meta.url));

// ------------------------------------------------------------------ arguments
const argv = process.argv.slice(2);
const flag = (name) => argv.includes(name);
const opt = (name, fallback) => {
    const i = argv.indexOf(name);
    if (i === -1) return fallback;
    const v = argv[i + 1];
    if (!v || v.startsWith("--")) die(`${name} needs a value`);
    return v;
};
function die(msg) {
    console.error(`review-kit: ${msg}`);
    process.exit(1);
}

if (flag("--help") || flag("-h")) {
    console.log(readFileSync(fileURLToPath(import.meta.url), "utf8").split("\n").slice(1, 30).join("\n").replace(/^\/\/ ?/gm, ""));
    process.exit(0);
}

/** Drop any trailing slashes, without a regex that can backtrack on a long run of them. */
const stripTrailingSlashes = (s) => {
    let end = s.length;
    while (end > 0 && s[end - 1] === "/") end -= 1;
    return s.slice(0, end);
};

const TARGET = resolve(opt("--target", process.cwd()));
const DOCS = stripTrailingSlashes(opt("--docs-root", "docs/agents"));
const AGENTS = stripTrailingSlashes(opt("--agents-root", ".claude/agents"));
const REVIEW_DIR = stripTrailingSlashes(opt("--review-dir", ".review"));
const TRIGGER = opt("--trigger", "@claude deep-review");
const CORPUS = opt("--corpus", flag("--no-corpus") ? "none" : "native");
if (!["native", "aidd", "none"].includes(CORPUS)) die(`--corpus must be native, aidd or none`);
const NATIVE_CORPUS = CORPUS === "native";
const VENDOR = !flag("--no-vendor");
const WORKFLOW = !flag("--no-workflow");
const LINK_AGENTS_MD = !flag("--no-agents-md");
const FORCE = flag("--force");
const DRY = flag("--dry-run");

if (!existsSync(TARGET)) die(`no such directory: ${TARGET}`);
if (!existsSync(join(TARGET, ".git"))) console.log(`  warn  ${TARGET} is not a git repository`);
if (resolve(KIT) === resolve(TARGET)) die("the target is the kit itself");

// ------------------------------------------------------------------ helpers
const written = [];
const skipped = [];

/** Paths and prose in the templates assume the defaults; rewrite both when they were overridden. */
function substitute(text, file) {
    let out = text.split("@claude deep-review").join(TRIGGER);
    if (DOCS !== "docs/agents") out = out.split("docs/agents/").join(`${DOCS}/`);
    if (AGENTS !== ".claude/agents") out = out.split(".claude/agents/").join(`${AGENTS}/`);
    if (REVIEW_DIR !== ".review") out = out.split(".review/").join(`${REVIEW_DIR}/`);
    if (file.endsWith("review.config.json")) {
        const cfg = JSON.parse(out);
        Object.assign(cfg, { docsRoot: DOCS, agentsRoot: AGENTS, reviewDir: REVIEW_DIR, trigger: TRIGGER });
        out = `${JSON.stringify(cfg, null, 2)}\n`;
    }
    return out;
}

function put(relPath, contents) {
    const dest = join(TARGET, relPath);
    if (existsSync(dest) && !FORCE) {
        skipped.push(relPath);
        return;
    }
    written.push(relPath);
    if (DRY) return;
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, contents);
}

// The extensions whose contents get the default-path substitution; anything else is copied raw.
const SUBSTITUTED_EXT = [".md", ".json", ".yaml", ".yml", ".js", ".mjs", ".txt"];

function copy(from, relPath) {
    const raw = readFileSync(from);
    const text = SUBSTITUTED_EXT.some((ext) => from.endsWith(ext)) ? substitute(raw.toString("utf8"), from) : raw;
    put(relPath, text);
}

function walk(dir, onFile, prefix = "") {
    for (const name of readdirSync(dir)) {
        if (name === ".git" || name === "node_modules") continue;
        const full = join(dir, name);
        const rel = prefix ? `${prefix}/${name}` : name;
        if (statSync(full).isDirectory()) walk(full, onFile, rel);
        else onFile(full, rel);
    }
}

// ------------------------------------------------------------------ the runtime
const CORPUS_SKILLS = [".claude/skills/doc-lint/", ".claude/skills/dev-context/"];
walk(join(KIT, "runtime"), (full, rel) => {
    if (!WORKFLOW && rel.startsWith(".github/workflows/")) return;
    // doc-lint and dev-context serve any corpus; only the hand-written scaffolding is native-only.
    if (CORPUS === "none" && CORPUS_SKILLS.some((d) => rel.startsWith(d))) return;
    let dest = rel;
    if (rel.startsWith("docs/agents/")) dest = rel.replace(/^docs\/agents\//, `${DOCS}/`);
    else if (rel.startsWith(".claude/agents/")) dest = rel.replace(/^\.claude\/agents\//, `${AGENTS}/`);
    copy(full, dest);
});

// ------------------------------------------------------------------ starter config and register
copy(join(KIT, "templates/docs/review.config.json"), `${DOCS}/review.config.json`);
copy(join(KIT, "templates/docs/review-ownership.json"), `${DOCS}/review-ownership.json`);
copy(join(KIT, "templates/docs/rules-doc.md"), `${DOCS}/review-templates/rules-doc.md`);

// The corpus the reviewers cite and the coding agents read. Same rules, two consumers.
//
// Only the native mode scaffolds documents: a generated corpus already has its own layout, its own
// index and its own generator, and writing into it would be overwritten on the next run.
if (NATIVE_CORPUS) {
    copy(join(KIT, "templates/docs/INDEX.md"), `${DOCS}/INDEX.md`);
    copy(join(KIT, "templates/docs/routing.yml"), `${DOCS}/routing.yml`);
    copy(join(KIT, "templates/docs/glossary.md"), `${DOCS}/glossary.md`);
}

// The corpus preset is merged into the config rather than shipped as a second file: one place
// answers "where do the rules live here".
if (CORPUS !== "none") {
    const cfgPath = join(TARGET, `${DOCS}/review.config.json`);
    if (existsSync(cfgPath)) {
        const cfg = JSON.parse(readFileSync(cfgPath, "utf8"));
        if (!cfg.corpus || FORCE) {
            const preset = JSON.parse(readFileSync(join(KIT, `templates/presets/${CORPUS}.json`), "utf8"));
            cfg.corpus = preset.corpus;
            cfg.coverageNotes = { ...cfg.coverageNotes, ...preset.coverageNotes };
            if (!DRY) writeFileSync(cfgPath, `${JSON.stringify(cfg, null, 2)}\n`);
            written.push(`${DOCS}/review.config.json (corpus: ${CORPUS})`);
        } else {
            skipped.push(`${DOCS}/review.config.json (already declares a corpus)`);
        }
    }
}

// Every agent template stays in the repo: adding an axis later must not need the kit again.
walk(join(KIT, "templates/agents"), (full, rel) => copy(full, `${DOCS}/review-templates/agents/${rel}`));

// The three that exist in every pipeline. integration is complete as shipped; the other two carry
// review-kit:todo markers where this repo's specifics belong.
for (const a of ["integration", "general", "complexity"]) {
    copy(join(KIT, `templates/agents/${a}-reviewer.md`), `${AGENTS}/${a}-reviewer.md`);
}

// ------------------------------------------------------------------ the kit itself
if (VENDOR && resolve(KIT) !== resolve(join(TARGET, "tools/review-kit"))) {
    walk(KIT, (full, rel) => {
        if (rel.startsWith("runtime/") || rel.startsWith("templates/")) return; // already installed
        copy(full, `tools/review-kit/${rel}`);
    });
    // The sources the vendored copy needs to install another repo, byte for byte.
    for (const sub of ["runtime", "templates"]) {
        walk(join(KIT, sub), (full, rel) => {
            const dest = join(TARGET, `tools/review-kit/${sub}/${rel}`);
            if (existsSync(dest) && !FORCE) return skipped.push(`tools/review-kit/${sub}/${rel}`);
            written.push(`tools/review-kit/${sub}/${rel}`);
            if (DRY) return;
            mkdirSync(dirname(dest), { recursive: true });
            writeFileSync(dest, readFileSync(full)); // verbatim: no substitution in the kit's own copy
        });
    }
}

// ------------------------------------------------------------------ gitignore
const giPath = join(TARGET, ".gitignore");
const gi = existsSync(giPath) ? readFileSync(giPath, "utf8") : "";
if (!gi.split("\n").some((l) => l.trim().replace(/\/$/, "") === REVIEW_DIR)) {
    if (!DRY) writeFileSync(giPath, `${gi}${gi.endsWith("\n") || !gi ? "" : "\n"}\n# Review pipeline run artefacts\n${REVIEW_DIR}/\n`);
    written.push(".gitignore (+ run artefacts)");
}

// ------------------------------------------------------------------ the agent-agnostic pointer
const BEGIN = "<!-- review-kit:begin -->";
const END = "<!-- review-kit:end -->";

/** The pointer lines that depend on where this repo's rules live. */
function corpusPointerLines() {
    if (NATIVE_CORPUS)
        return [
            `- Before writing code: the \`dev-context\` skill, which routes the task through`,
            `  \`${DOCS}/routing.yml\` and loads the rules that govern it — the same rules the reviewers cite.`,
            `- The map of the rule docs: \`${DOCS}/INDEX.md\`.`,
        ];
    if (CORPUS === "aidd")
        return [
            `- The rules live in the generated corpus (AIDD). \`node .github/scripts/review-corpus.js\``,
            `  lists them; \`--match <files>\` shows which ones a change engages. Never edit them here.`,
        ];
    return [];
}

const block = [
    BEGIN,
    "## Code review pipeline",
    "",
    `This repo reviews pull requests with a multi-agent pipeline. Before changing any part of it, read`,
    `\`${DOCS}/review-pipeline.md\` (how a review is produced) and \`${DOCS}/review-contract.md\` (how a`,
    `reviewer judges and reports).`,
    "",
    `- Run a review locally: the \`review-pr\` skill, or execute \`.claude/skills/review-pr/SKILL.md\`.`,
    `- Install, add or tune a reviewer axis: the \`review-kit\` skill, or execute`,
    `  \`${DOCS}/review-onboarding.md\`.`,
    `- Which reviewers exist here, and what routes them: \`${DOCS}/review.config.json\`.`,
    ...corpusPointerLines(),
    `- After changing any of it: \`node .github/scripts/review-doctor.js --all\`.`,
    END,
].join("\n");

if (LINK_AGENTS_MD) {
    for (const name of ["AGENTS.md", "CLAUDE.md"]) {
        const p = join(TARGET, name);
        if (!existsSync(p)) continue;
        const body = readFileSync(p, "utf8");
        if (body.includes("Do not update this file")) continue; // a deliberate stub
        const next = body.includes(BEGIN)
            ? body.replace(new RegExp(String.raw`${BEGIN}[\s\S]*?${END}`), block)
            : `${body.trimEnd()}\n\n${block}\n`;
        if (next !== body) {
            if (!DRY) writeFileSync(p, next);
            written.push(`${name} (pointer block)`);
        }
    }
}

// ------------------------------------------------------------------ report
console.log(`${DRY ? "would install" : "installed"} into ${TARGET}\n`);
for (const f of written) console.log(`  +  ${f}`);
if (skipped.length) {
    console.log(`\n  ${skipped.length} file(s) left alone because they already exist (--force to overwrite):`);
    for (const f of skipped.slice(0, 12)) console.log(`  =  ${f}`);
    if (skipped.length > 12) console.log(`  =  … and ${skipped.length - 12} more`);
}

console.log(`
Next, and none of it is optional - the runtime is portable, the judgement is not:

  1. Read ${DOCS}/review-onboarding.md. It is the procedure, written for a human or an agent.
     In Claude Code:  /review-kit
     Anywhere else:   "read ${DOCS}/review-onboarding.md and execute it"
  2. It will survey the repo, choose the axes with you, write ${DOCS}/review.config.json,
     author one agent file per axis, and calibrate against a real pull request.
  3. Check the wiring:  node .github/scripts/review-doctor.js --all
     (--all also runs .claude/skills/doc-lint/check.mjs, which owns the doc tree's invariants)
  4. For CI, add CLAUDE_CODE_OAUTH_TOKEN as a repository secret, then comment
     "${TRIGGER}" on a pull request.

Until step 2 is done this repo has two generic reviewers and no local knowledge, which is a
pipeline that runs and finds very little.`);
